apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ledger-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/techno-rik/ledger-api-assignment
    targetRevision: HEAD
    path: deploy

  destination:
    server: https://kubernetes.default.svc
    namespace: payments

  syncPolicy:
    automated:
      prune: true
      selfHeal: true